GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY2Nzg1MzY1OH0.hW7XcP7c0OAFgtiSfL8D-EJIhW1p9khSMcwLywPJvX4

###

POST http://localhost:3000/login
Content-Type: text/html

{
    "username": "test4",
    "password": "test4",
}